authors:
  snowflake:
    name: Snowflake
    description: Snowflake blog
    avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Snowflake_Logo.svg/220px-Snowflake_Logo.svg.png
  celesteh:
    name: Celeste Horgan
    description: Snowflake OSS Advocate
    avatar: https://#  
